name: Run Pytest for FastAPI Automation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      backend:
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.10
        ports:
          - 8000:80
        volumes:
          - ./:/app
        options: >-
          --health-cmd="curl http://localhost:80/docs || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend..."
          sleep 20

      - name: Run tests
        run: pytest tests --maxfail=1 --disable-warnings -v
